name: Biome

on:
  pull_request:
  push:
    branches-ignore:
      - "renovate/**"
      - "dependabot/**"

concurrency:
  group: biome-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npx biome ci .
